// # - Routes barrel !
// autogenerated file based on files inside routes folder!
export { Another } from './about.route';
export { default as NotAboutRoute } from './about.route';
export { LandingRoute } from './landing.route';
export { SubRoute } from './subroutesfolder/subroute.route';
